### Create room
POST http://localhost:8080/room/create
Content-Type: application/json

{
  "capacity": 3,
  "difficulty": "easy",
  "category": 15
}

### Get game content
GET http://localhost:8080/room/game?code=0GZGaw