version: "3"

services:
  postgres:
    image: postgres:15.4
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgres/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=qwerty12345
      - POSTGRES_USER=main
      - POSTGRES_DB=quizz_server
    restart: unless-stopped

  spring:
    image: app
    network_mode: bridge
    container_name: quizz_server
    environment:
      - SPRING_DATASOURCE_URL = jdbc:postgresql://postgres:5432/quizz_server
      - SPRING_LIQUIBASE_URL = jdbc:postgres://postgres:5432/quizz_server
      - SPRING_LIQUIBASE_ENABLED = false
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres-data: