### Create room
POST http://localhost:8080/api/room/create
Content-Type: application/json

{
  "capacity": 3,
  "difficulty": "easy",
  "category": 15
}

### Get game content
GET http://localhost:8080/api/room/game?code=ShzJQq
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlMkBtYWlsLnJ1IiwiZXhwIjoxNzE2MjMxNzI5LCJyb2xlcyI6WyJVU0VSIl0sInVzZXJuYW1lIjoiYWlzIn0.iYgU-s0OpVugU7MF_tghpT_iGLxnTOaOKkc_JXLam4s


### Get all
GET http://localhost:8080/api/room/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlMkBtYWlsLnJ1IiwiZXhwIjoxNzE2MDU3NDc2LCJyb2xlcyI6WyJVU0VSIl0sInVzZXJuYW1lIjoiYWlzeWx1In0.95raOCmg_NUPCCKjubyJ8v8ZZfxrSX-AIBoQyxnG68Y