### Registration
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "email": "u@gmail.com",
  "password": "password1108"
}


### Update username
GET http://localhost:8080/api/user/update/name?id=2&name=ais
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlMkBtYWlsLnJ1IiwiZXhwIjoxNzE2NzI2MTIxLCJyb2xlcyI6WyJVU0VSIl0sInVzZXJuYW1lIjoiYWlzIn0._zWM0VYDkW9gU79chM6TEKir7EaWBUE9DG2ESDUiNd8



